### PR TITLE
L10n fr

### PR DESCRIPTION
**Pull request by tdd**
Hey again,

As mentioned in #56, this is the second step of our recent work on globalizing and localizing `expressworks`. This includes the commits referenced in #56, which will "disappear" when/if you merge that one first, to leave only FR-related commits for actual localization.

I remain, naturally, available for any discussion on this.

Looking forward to our getting that in,

Best,

### CODE REVIEW

**Comment by tdd** [comment]
And yay, this auto-merges again!

**Comment by azat-co** [comment]
@tdd I merged both PRs and published at 2.0.0... thank you! can you double check it again? or during your nodeschool event?

**Comment by tdd** [comment]
Hey Azat, thanks a ton! npm does show the package.

I realize perhaps it's time to update that screenshot from the README :wink:

**Comment by azat-co** [comment]
haha

**Pull request merged**
